### CREER UN USER

POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "email": "admin2@test.com",
    "password": "Password234$$$",
    "isAdmin": true,
    "isCandidate": false,
    "isBanned": false
}

### SIGNIN

POST http://localhost:3000/users/signin
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "Password234$$$"
}

### SIGNOUT

POST http://localhost:3000/users/signout

### GET ALL USERS

GET http://localhost:3000/users/all

### GET ONE USER

GET http://localhost:3000/users/1

### CHANGE ONE TO CANDIDATE

POST http://localhost:3000/users/changeOneToCandidate
Content-Type: application/json

{
    "userId": 1,
    "isCandidate": false 
}